# Generated by Django 5.1.7 on 2025-03-27 17:35

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abonnement',
            options={'verbose_name': 'abonnement', 'verbose_name_plural': 'abonnements'},
        ),
        migrations.AlterModelOptions(
            name='annonce',
            options={'verbose_name': 'annonce', 'verbose_name_plural': 'annonces'},
        ),
        migrations.AlterModelOptions(
            name='boxstockage',
            options={'verbose_name': 'box de stockage', 'verbose_name_plural': 'boxes de stockage'},
        ),
        migrations.AlterModelOptions(
            name='calendrierdisponibilite',
            options={'verbose_name': 'disponibilité', 'verbose_name_plural': 'disponibilités'},
        ),
        migrations.AlterModelOptions(
            name='commercant',
            options={'verbose_name': 'commerçant', 'verbose_name_plural': 'commerçants'},
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'verbose_name': 'contrat', 'verbose_name_plural': 'contrats'},
        ),
        migrations.AlterModelOptions(
            name='entrepot',
            options={'verbose_name': 'entrepôt', 'verbose_name_plural': 'entrepôts'},
        ),
        migrations.AlterModelOptions(
            name='evaluation',
            options={'verbose_name': 'évaluation', 'verbose_name_plural': 'évaluations'},
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'verbose_name': 'facture', 'verbose_name_plural': 'factures'},
        ),
        migrations.AlterModelOptions(
            name='livraison',
            options={'verbose_name': 'livraison', 'verbose_name_plural': 'livraisons'},
        ),
        migrations.AlterModelOptions(
            name='livreur',
            options={'verbose_name': 'livreur', 'verbose_name_plural': 'livreurs'},
        ),
        migrations.AlterModelOptions(
            name='logconnexion',
            options={'verbose_name': 'log de connexion', 'verbose_name_plural': 'logs de connexion'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name': 'notification', 'verbose_name_plural': 'notifications'},
        ),
        migrations.AlterModelOptions(
            name='paiement',
            options={'verbose_name': 'paiement', 'verbose_name_plural': 'paiements'},
        ),
        migrations.AlterModelOptions(
            name='piecejustificative',
            options={'verbose_name': 'pièce justificative', 'verbose_name_plural': 'pièces justificatives'},
        ),
        migrations.AlterModelOptions(
            name='prestataire',
            options={'verbose_name': 'prestataire', 'verbose_name_plural': 'prestataires'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'utilisateur', 'verbose_name_plural': 'utilisateurs'},
        ),
        migrations.AddField(
            model_name='abonnement',
            name='auto_renouvellement',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='est_urgente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='annonce',
            name='vues',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='calendrierdisponibilite',
            name='recurrence',
            field=models.CharField(choices=[('none', 'Aucune'), ('daily', 'Quotidienne'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuelle')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='commercant',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Taux de commission en pourcentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='contrat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contrats_crees', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_creation',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrat',
            name='date_signature',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrepots_geres', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='livreur',
            name='date_inscription',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='livreur',
            name='nombre_livraisons',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='logconnexion',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='logconnexion',
            name='reussi',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='lien',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='type_notification',
            field=models.CharField(choices=[('info', 'Information'), ('success', 'Succès'), ('warning', 'Avertissement'), ('error', 'Erreur')], default='info', max_length=10),
        ),
        migrations.AddField(
            model_name='paiement',
            name='date_derniere_mise_a_jour',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='validee_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_pieces', to='dashboard.user'),
        ),
        migrations.AddField(
            model_name='prestataire',
            name='nombre_services',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='duree_estimee',
            field=models.IntegerField(default=60, help_text='Durée estimée en minutes', validators=[django.core.validators.MinValueValidator(15)]),
        ),
        migrations.AddField(
            model_name='service',
            name='zone_intervention',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_derniere_connexion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='langue_preference',
            field=models.CharField(default='fr', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='portefeuille_solde',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='commercant',
            name='siret',
            field=models.CharField(max_length=14, validators=[django.core.validators.RegexValidator('^\\d{14}$', message='Le SIRET doit comporter 14 chiffres')]),
        ),
        migrations.AlterField(
            model_name='evaluation',
            name='note',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='facture',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='factures/'),
        ),
        migrations.AlterField(
            model_name='livreur',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='prestataire',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{9,15}$', message='Format de téléphone invalide')]),
        ),
        migrations.AlterUniqueTogether(
            name='boxstockage',
            unique_together={('entrepot', 'reference')},
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['status', 'type_annonce'], name='dashboard_a_status_6e328a_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['created_at'], name='dashboard_a_created_73cd97_idx'),
        ),
        migrations.AddIndex(
            model_name='annonce',
            index=models.Index(fields=['date_depart'], name='dashboard_a_date_de_ccb301_idx'),
        ),
        migrations.AddIndex(
            model_name='calendrierdisponibilite',
            index=models.Index(fields=['date_debut', 'date_fin'], name='dashboard_c_date_de_959c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='calendrierdisponibilite',
            index=models.Index(fields=['user', 'disponible'], name='dashboard_c_user_id_c7a93b_idx'),
        ),
        migrations.AddIndex(
            model_name='commercant',
            index=models.Index(fields=['siret'], name='dashboard_c_siret_494ae0_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['reference'], name='dashboard_c_referen_5afb17_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['status'], name='dashboard_c_status_cac925_idx'),
        ),
        migrations.AddIndex(
            model_name='contrat',
            index=models.Index(fields=['date_debut'], name='dashboard_c_date_de_5746a6_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['evaluateur', 'evalue'], name='dashboard_e_evaluat_63bcb2_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['note'], name='dashboard_e_note_e5f724_idx'),
        ),
        migrations.AddIndex(
            model_name='evaluation',
            index=models.Index(fields=['date_evaluation'], name='dashboard_e_date_ev_03f9f9_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['reference'], name='dashboard_f_referen_d1fd6c_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date_emission'], name='dashboard_f_date_em_cada8a_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['reference'], name='dashboard_l_referen_d6dc84_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['status'], name='dashboard_l_status_a3a2dc_idx'),
        ),
        migrations.AddIndex(
            model_name='livraison',
            index=models.Index(fields=['date_livraison_prevue'], name='dashboard_l_date_li_5951fb_idx'),
        ),
        migrations.AddIndex(
            model_name='logconnexion',
            index=models.Index(fields=['user', 'date_connexion'], name='dashboard_l_user_id_da4988_idx'),
        ),
        migrations.AddIndex(
            model_name='logconnexion',
            index=models.Index(fields=['adresse_ip'], name='dashboard_l_adresse_ad36bd_idx'),
        ),
        migrations.AddIndex(
            model_name='logconnexion',
            index=models.Index(fields=['reussi'], name='dashboard_l_reussi_d1a359_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'lue'], name='dashboard_n_user_id_339ea1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['date_creation'], name='dashboard_n_date_cr_78718a_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['reference'], name='dashboard_p_referen_d933a7_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['status'], name='dashboard_p_status_bbef8e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['type_service', 'disponible'], name='dashboard_s_type_se_7bb88e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='dashboard_u_usernam_72d18e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='dashboard_u_email_f6364d_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='dashboard_u_user_ty_746798_idx'),
        ),
    ]
