# Generated by Django 5.1.7 on 2025-04-18 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_abonnement_options_alter_annonce_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeValidationLivreur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('en_attente', 'En attente'), ('en_examen', "En cours d'examen"), ('validee', 'Validée'), ('refusee', 'Refusée')], default='en_attente', max_length=15)),
                ('motif_refus', models.TextField(blank=True, null=True)),
                ('notes_admin', models.TextField(blank=True, null=True)),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validations_livreurs_traitees', to='dashboard.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_validation_livreur', to='dashboard.user')),
            ],
            options={
                'verbose_name': 'demande de validation livreur',
                'verbose_name_plural': 'demandes de validation livreur',
            },
        ),
        migrations.AddField(
            model_name='livreur',
            name='derniere_demande_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livreur', to='dashboard.demandevalidationlivreur'),
        ),
        migrations.AddField(
            model_name='piecejustificative',
            name='demande_validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='dashboard.demandevalidationlivreur'),
        ),
        migrations.AddIndex(
            model_name='demandevalidationlivreur',
            index=models.Index(fields=['status'], name='dashboard_d_status_878110_idx'),
        ),
        migrations.AddIndex(
            model_name='demandevalidationlivreur',
            index=models.Index(fields=['date_demande'], name='dashboard_d_date_de_15f0a7_idx'),
        ),
    ]
