# Generated by Django 5.1.7 on 2025-05-30 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_demandevalidationlivreur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieEtapeTutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('type_utilisateur', models.CharField(choices=[('admin', 'Administrateur'), ('livreur', 'Livreur'), ('client', 'Client'), ('commercant', 'Commerçant'), ('prestataire', 'Prestataire')], max_length=20)),
                ('ordre', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "Catégorie d'étape tutoriel",
                'verbose_name_plural': "Catégories d'étapes tutoriel",
                'ordering': ['type_utilisateur', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='CategorieTraduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Catégorie de traduction',
                'verbose_name_plural': 'Catégories de traductions',
            },
        ),
        migrations.CreateModel(
            name='LangueDisponible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('nom_natif', models.CharField(max_length=50)),
                ('nom_francais', models.CharField(max_length=50)),
                ('active', models.BooleanField(default=True)),
                ('ordre_affichage', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Langue disponible',
                'verbose_name_plural': 'Langues disponibles',
                'ordering': ['ordre_affichage', 'nom_francais'],
            },
        ),
        migrations.CreateModel(
            name='CleTraduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(db_index=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text="Description du contexte d'utilisation")),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cles', to='dashboard.categorietraduction')),
            ],
            options={
                'verbose_name': 'Clé de traduction',
                'verbose_name_plural': 'Clés de traductions',
            },
        ),
        migrations.CreateModel(
            name='EtapeTutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField()),
                ('ordre', models.IntegerField()),
                ('type_etape', models.CharField(choices=[('modal', 'Modal/Pop-up'), ('overlay', 'Overlay'), ('tooltip', 'Info-bulle'), ('highlight', 'Mise en évidence'), ('video', 'Vidéo'), ('interactive', 'Interactif')], max_length=20)),
                ('element_cible', models.CharField(blank=True, help_text="Sélecteur CSS de l'élément à cibler", max_length=255)),
                ('position', models.CharField(choices=[('top', 'Haut'), ('bottom', 'Bas'), ('left', 'Gauche'), ('right', 'Droite'), ('center', 'Centre')], default='bottom', max_length=10)),
                ('obligatoire', models.BooleanField(default=True, help_text="L'utilisateur doit-il compléter cette étape ?")),
                ('skippable', models.BooleanField(default=False, help_text="L'utilisateur peut-il passer cette étape ?")),
                ('auto_next', models.BooleanField(default=False, help_text="Passe automatiquement à l'étape suivante")),
                ('duree_auto', models.IntegerField(default=0, help_text="Durée en secondes pour l'auto-passage (0 = désactivé)")),
                ('url_page', models.CharField(help_text='URL de la page où afficher cette étape', max_length=255)),
                ('condition_affichage', models.TextField(blank=True, help_text="Condition JavaScript pour afficher l'étape")),
                ('image', models.ImageField(blank=True, null=True, upload_to='tutoriel/images/')),
                ('video_url', models.URLField(blank=True)),
                ('config_avancee', models.JSONField(blank=True, default=dict, help_text='Configuration JSON pour des options avancées')),
                ('active', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='dashboard.categorieetapetutoriel')),
            ],
            options={
                'verbose_name': 'Étape de tutoriel',
                'verbose_name_plural': 'Étapes de tutoriel',
                'ordering': ['categorie__type_utilisateur', 'categorie__ordre', 'ordre'],
            },
        ),
        migrations.CreateModel(
            name='PreferenceLangueUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('langue_documents', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_documents', to='dashboard.languedisponible')),
                ('langue_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_interface', to='dashboard.languedisponible')),
                ('langue_notifications', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='utilisateurs_notifications', to='dashboard.languedisponible')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_langue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférence de langue',
                'verbose_name_plural': 'Préférences de langues',
            },
        ),
        migrations.CreateModel(
            name='ProgressionTutoriel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('non_commence', 'Non commencé'), ('en_cours', 'En cours'), ('complete', 'Terminé'), ('abandonne', 'Abandonné'), ('reporte', 'Reporté')], default='non_commence', max_length=20)),
                ('premiere_connexion_date', models.DateTimeField(auto_now_add=True)),
                ('tutoriel_commence_date', models.DateTimeField(blank=True, null=True)),
                ('tutoriel_termine_date', models.DateTimeField(blank=True, null=True)),
                ('afficher_au_login', models.BooleanField(default=True, help_text='Afficher le tutoriel à la prochaine connexion')),
                ('peut_etre_relance', models.BooleanField(default=True, help_text="L'utilisateur peut-il relancer le tutoriel")),
                ('nombre_relances', models.IntegerField(default=0)),
                ('temps_total_seconde', models.IntegerField(default=0)),
                ('derniere_etape', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derniere_etape_utilisateurs', to='dashboard.etapetutoriel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progression_tutoriel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progression tutoriel',
                'verbose_name_plural': 'Progressions tutoriel',
            },
        ),
        migrations.CreateModel(
            name='ProgressionEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('duree_seconde', models.IntegerField(default=0)),
                ('completee', models.BooleanField(default=False)),
                ('skippee', models.BooleanField(default=False)),
                ('nombre_clics', models.IntegerField(default=0)),
                ('nombre_retours', models.IntegerField(default=0)),
                ('utile', models.BooleanField(blank=True, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('etape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='dashboard.etapetutoriel')),
                ('progression', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes_completees', to='dashboard.progressiontutoriel')),
            ],
            options={
                'verbose_name': "Progression d'étape",
                'verbose_name_plural': "Progressions d'étapes",
            },
        ),
        migrations.CreateModel(
            name='Traduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('validee', models.BooleanField(default=False)),
                ('cle_traduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions', to='dashboard.cletraduction')),
                ('langue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traductions', to='dashboard.languedisponible')),
                ('traduit_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traductions_effectuees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traduction',
                'verbose_name_plural': 'Traductions',
            },
        ),
        migrations.AddIndex(
            model_name='cletraduction',
            index=models.Index(fields=['cle'], name='dashboard_c_cle_1c4728_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='etapetutoriel',
            unique_together={('categorie', 'ordre')},
        ),
        migrations.AlterUniqueTogether(
            name='progressionetape',
            unique_together={('progression', 'etape')},
        ),
        migrations.AddIndex(
            model_name='traduction',
            index=models.Index(fields=['cle_traduction', 'langue'], name='dashboard_t_cle_tra_99bb49_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='traduction',
            unique_together={('cle_traduction', 'langue')},
        ),
    ]
